affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 20
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 8
symbolic.funs_name.0:
- - x
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - x
  - sin
  - x
  - x
  - sin
  - sin
- - x
  - sin
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
- - x
  - x
  - '0'
  - '0'
  - x
  - x
  - x
  - x
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - sin
- - x
  - '0'
  - x
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - '0'
  - sin
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
- - x
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - x
  - x
  - '0'
  - '0'
symbolic.funs_name.1:
- - sin
  - x
  - x
  - x
  - '0'
  - sin
  - x
symbolic_enabled: true
width:
- - 14
  - 0
- - 7
  - 0
- - 1
  - 0
